### ISSUE TITLE
EventListener in FlxButton and FlxGroup is still active after set to false

### ISSUE THREAD

**Issue by WingEraser** [FlixelCommunity/flixel#162] opened 2013-03-23 13:58 UTC
``` as3
group = new FlxGroup();
add(group );

button = new FlxButton(50, 50, "Text", onClick);
group.add(button);


private function onClick():void
{
    group.active = false;
    trace("it still got fired");
}
```

Click once on the button. The group where the button belongs will be deactivated. Now click anywhere on the stage and you'll see the the onClick is (still) fired.
Deactivate the button itself will prevent the firing the onClick.

**Comment by greysondn** [comment] 2013-03-28 14:04
I don't have time to pour over the documentation and codebase right now, but the first and sort of obvious question to my mind is: Do you know for sure what you're doing here? Active is not about event listeners but rather the Flixel standard update() step. (See: http://flixel.org/docs/org/flixel/FlxBasic.html#active for the one that eventually is used in FlxGroup)

Being said, that doesn't mean that your underlying expectation is necessarily bad - why would you want events to fire off if you set active to false? The only question is if you really understand what's going on here.

Suggest: Finding someway to unregister event listeners on deactivation. Someone will still need to review the code to see what's really going on here, at the most core level.

**Comment by WingEraser** [comment] 2013-03-28 15:28
I know what's going on.
For FlxButton active is to prevent to fire a event onUp.

``` as3
protected function onMouseUp(event:MouseEvent):void
{
    if(!exists || !visible || !active || (status != PRESSED))
        return;
    if(onUp != null)
        onUp();
    if(soundUp != null)
        soundUp.play(true);
}
```

That's the reason why it works. There is no need to get rid off the event listener, when deactivate.

When you deactivate a FlxGroup with FlxButtons, the button itself is active.
FlxGroup doesn't update the children when deactived, but the event listener is still active. And because it's a MouseEvent it can always fire an event.

It can be a bug if you see it like this: when deactive a group with buttons, the user expect the button doesn't work anymore. Well the button doesn't get updated anymore, so you shouldn't expect the button still can fire an event.

Solution: deactivate the children. It can be done with FlxGroup::setAll(), but I don't think user will come up with this in the first place.

**Comment by greysondn** [comment] 2013-03-28 19:59
_chuckles_ As I had said earlier, I didn't have time to review the code relevant here.

I don't necessarily think that the solution, however, is to set all children inactive, as group members can be in more than one group. Let's find a solution, though :3

I'm going to think over this, but AS3 is admittedly not my strong suit by any stretch of the imagination. There must be some way. Ah the hazards of just getting your hands dirty. I apologize for the trainwreck I caused there.

**Comment by WingEraser** [comment] 2013-03-28 20:10
No worries.
The FlxGroup::setAll() tackles group inside group already.

**Comment by greysondn** [comment] 2013-03-28 21:49
No, no - I mean the case where the flxbutton is a member of more than one flxgroup XD it seems like wontonly disabling each member would make the other group the flxbutton is in have unexpected behavior - that button wouldn't match the second group's active setting.

**Comment by WingEraser** [comment] 2013-03-28 22:05
Lol XD, never added an object in different groups. Just tried, the behaviour is expected. When group 1  is inactive and group 2 is active. The button will render as normal instead inactive. And of course the event will be fired.
When the button is active is set to false directly, it will be alright in both groups. It's inactive and that's what you should expect.

**Comment by greysondn** [comment] 2013-03-28 22:34
_facepalms_ We both need coffee, methinks. I'll do some testing next time I'm writing code and see what happens here.

**Comment by Dovyski** [comment] 2013-08-21 16:28
As @greysondn pointed out, it's not a bug if we think any group member might be part of another group. I've never done that, but any `FlxSprite` can be a member of several groups at the same time, so `FlxGroup` should not "interfere" with any of its members, since that interference will affect the other groups.

If we decide to propagate to the children any change made in the parent group, then we must forbid sprites from being members of more than one groups at the time.

**Comment by greysondn** [comment] 2013-08-21 20:13
Incidental example from my own code right now as to why this matters:

I have an enemy of sorts that can interact with the player's units indirectly, and that interaction's persistence is based largely on whether the player is interacting with ANY of the enemies of that type any longer. But the larger collection of enemies also matters for various reasons and so it's separate.

That is, I have ants and I have holes - and while all the ants and holes together matter, the ants as an individual group and the holes as an individual group also do. At that point, I just need a list that I can quickly and easily collide against, and need update on the master list (of all enemies of all types together) but not on the individual lists (of all enemies of one type together).

So.... There is at least one valid usecase for them to be in multiple groups, with different conditions imposed on each group in such a way that combining them under a parent isn't simple.

My code hasn't been optimized and I may as yet find a better way to do that. But the point is that I don't think disabling the ability to be in multiple groups is the solution. You never know where you'll end up at XD

**Comment by greysondn** [comment] 2013-08-21 20:17
I'll bring up the "NDA getting in the way of helping and explaining things upstream" issue at our next meeting, and apologize for that in the meantime. It's super easy to understand if I can just post scraps of code for you :(

**Comment by Dovyski** [comment] 2013-08-21 20:23
There is no need for scraps of code, @greysondn , I understood your case :) I agree that the the ability to be in multiple groups is useful and should not be removed/changed.

**Comment by Dovyski** [comment] 2013-09-23 13:25
Ok, guys, we had a lot of discussion here :) The issue has been quiet for about a month and I think the final thought is that `FlxGroup` should **_not**_ change any of its members, because they can be part of another group at the same time.

If anyone disagrees with that, please share your thoughts. I will close the issue within the next days if nothing happens.

**Closed as completed** 2013-10-08 23:35 UTC
Labels: wontfix
